# Generated by Django 5.2.8 on 2025-12-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
